name: gitops-update
description: Reusable GitHub Action to update a YAML file and commit the result
author: hello@masterpoint.io

inputs:
  new_value:
    description: New value that should replace the existing value at the given YAML path
    required: true
  yaml_key_path:
    description: Path to the YAML key that should be updated within the given YAML file
    required: true
  yaml_file_path:
    description: Path to the YAML file that should be updated
    required: true
  commit_message:
    description: Commit message that should be used when committing the changes
    required: true
  commit_username:
    description: The username of the user that will execute the commit.
    default: github-actions
    required: false
  commit_email:
    description: The email of the user that will execute the commit.
    default: github-actions@github.com
    required: false
  target_branch:
    description: The branch that should be pushed to
    default: ${{ github.event.repository.default_branch }}
    required: false
  github_token:
    description: The GitHub token used to commit and push the gitops changes (unnecessary if you don't have branch protections enabled on your target branch)
    default: ${{ github.token }}
    required: false

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

    - name: 🏗 Set up yq
      uses: frenck/action-setup-yq@c4b5be8b4a215c536a41d436757d9feb92836d4f # v1.0.2

    - name: Update YAML file + Commit + Push
      shell: bash
      run: |
        echo "Updating file"
        # Have to include a goofy diff / patch workaround to deal yq removing all whitespace newlines
        # See https://github.com/mikefarah/yq/issues/515#issuecomment-1113957629
        # Ugh, I need to add the "File updated successfully" to get the patch to work...
        yq '${{ inputs.yaml_key_path }} = "${{ inputs.new_value }}"' '${{ inputs.yaml_file_path }}' | diff -B '${{ inputs.yaml_file_path }}' - | patch --silent '${{ inputs.yaml_file_path }}' - && echo "File updated successfully"

        echo "Git config setup"
        git config user.name ${{ inputs.commit_username }}
        git config user.email ${{ inputs.commit_email }}

        echo "Committing and pushing changes"
        git add ${{ inputs.yaml_file_path }}
        git commit --allow-empty -m "ci(gitops): ${{ inputs.commit_message }}"
        git push -u origin ${{ inputs.target_branch }}
